default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: artemis_development

test:
  <<: *default
  database: artemis_test

production:
  <<: *default
  database: artemis_production
  username: artemis
  password: <%= ENV['ARTEMIS_DATABASE_PASSWORD'] %>
